# Generated by Django 5.0.4 on 2024-04-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0004_cart_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Users'), ('dealer', 'Dealer'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
